
import java.sql.CallableStatement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
import java.sql.SQLException;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.CallableStatement;
//mport javax.lang.model.util.Types;
import java.sql.Types;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Person.Attendance;
/**
 *
 * @author Shahnawaz Ali Raja
 */
public class Attendencetime extends javax.swing.JFrame {
java.sql.Connection con=null;
String Name=null;
Object year=null;
Object month=null;
Object date=null;
int checkin=0;
int checkout=0;
Object Timemode1=null;
Object Timemode2=null;
CallableStatement csmt2=null;
int status=0;

    /**
     * Creates new form Attendencetime
     */
    public Attendencetime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Year = new javax.swing.JComboBox<>();
        Checkout = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        confirm1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        time2 = new javax.swing.JComboBox<>();
        Month = new javax.swing.JComboBox<>();
        time1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Date = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Checkin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Year>", "2021", "2022", "2023", "2024", "2025", " " }));
        Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearActionPerformed(evt);
            }
        });
        jPanel1.add(Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, 20));

        Checkout.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(Checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel4.setText("Enter check-out time:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, 20));

        name.setForeground(new java.awt.Color(51, 51, 255));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel5.setText("Enter check-in time:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 20));

        Cancel.setBackground(new java.awt.Color(51, 51, 255));
        Cancel.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 51, 51));
        Cancel.setText("CANCEL");
        Cancel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 102)));
        Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 80, 30));

        confirm1.setBackground(new java.awt.Color(51, 51, 255));
        confirm1.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        confirm1.setForeground(new java.awt.Color(255, 51, 51));
        confirm1.setText("Confirm");
        confirm1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm1ActionPerformed(evt);
            }
        });
        jPanel1.add(confirm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 250, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel6.setText("Select Month:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 20));

        time2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Time Mode", "AM", "PM" }));
        time2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time2ActionPerformed(evt);
            }
        });
        jPanel1.add(time2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, 20));

        Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Month>", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthActionPerformed(evt);
            }
        });
        jPanel1.add(Month, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 120, 20));

        time1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Time Mode", "AM", "PM" }));
        time1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time1ActionPerformed(evt);
            }
        });
        jPanel1.add(time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 110, 20));

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel7.setText("Select Date:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 20));

        Date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Date>", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, 20));

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel8.setText("Select Year:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, 20));

        Checkin.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(Checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel11.setText("Enter name:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 330));

        jLabel3.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        jLabel3.setText("Attendence");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 270, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Attendence2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 290, 180));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attendance-management-system.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, -10, 630, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        Cashier_Dashboard db= new Cashier_Dashboard();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void confirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm1ActionPerformed
       
       Name=name.getText();
            year=Year.getSelectedItem();
            month=Month.getSelectedItem();
            date=Date.getSelectedItem();
            checkin=Integer.parseInt(Checkin.getText());
            checkout=Integer.parseInt(Checkout.getText());
            Timemode1=time1.getSelectedItem();
            Timemode2=time2.getSelectedItem();
            Attendance att=new Attendance();
           
    try {
        status= att.addAttendance(Name,year,month,date,checkin,checkout,Timemode1,Timemode2);
        
              if(status==0)
            {
                JOptionPane.showMessageDialog(null,"Attendence Recorded and Is marked Present");
                
                
            }
            if(status==1)
            {
                JOptionPane.showMessageDialog(null,"Attendence Recorded and Is marked Late");
            }
            if(status==2)
            {
                JOptionPane.showMessageDialog(null,"Attendence not marked");

            }
        // TODO add your handling code here:
    } 
    catch (Exception ex) 
    {
        //Logger.getLogger(Attendencetime.class.getName()).log(Level.SEVERE, null, ex);
    } 
        
        
    }//GEN-LAST:event_confirm1ActionPerformed

    private void time2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time2ActionPerformed

    private void MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthActionPerformed

    private void time1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time1ActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendencetime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendencetime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendencetime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendencetime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendencetime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField Checkin;
    private javax.swing.JTextField Checkout;
    private javax.swing.JComboBox<String> Date;
    private javax.swing.JComboBox<String> Month;
    private javax.swing.JComboBox<String> Year;
    private javax.swing.JButton confirm1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> time1;
    private javax.swing.JComboBox<String> time2;
    // End of variables declaration//GEN-END:variables
}
