/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.HeadlessException;
import java.sql.DriverManager;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
import java.sql.SQLException;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.CallableStatement;
//mport javax.lang.model.util.Types;
import java.sql.Types;
import Person.AddInventory;
/**
 *
 * @author Acer Laptop
 */
public class Inventory extends javax.swing.JFrame {
java.sql.Connection con=null;
String Barcode_NO=null;
int ProductID=0;
String ProductName=null;
String Categoryname=null;
int Quantity1=0;
float Cost_Price=0;
float Sales_Price=0;
String Description=null;
String spinner = "catch Value";
int status=0;
CallableStatement csmt=null;
AddInventory Data;
    /**
     * Creates new form Manage_Products
     */
    public Inventory() {
        initComponents();
        Data=new AddInventory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Barcode = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        productID = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cancel2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        costprice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        salesprice = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Category1 = new javax.swing.JTextField();
        remove = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        submit1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage_Inventory");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(78, 78, 78));
        jPanel1.setForeground(new java.awt.Color(78, 78, 78));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(88, 66, 33));
        jLabel3.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 102));
        jLabel3.setText("Bar Code:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 94, -1));
        jPanel1.add(Barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 144, -1));

        cancel.setBackground(new java.awt.Color(215, 127, 50));
        cancel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(246, 214, 151));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 358, -1, 23));

        jLabel8.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 102));
        jLabel8.setText("Product ID:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 78, -1));

        jLabel9.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 102));
        jLabel9.setText("Product Name:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 113, -1));

        productID.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        productID.setForeground(new java.awt.Color(51, 51, 51));
        productID.setAlignmentY(0.0F);
        productID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIDActionPerformed(evt);
            }
        });
        jPanel1.add(productID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, -1));

        productName.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        productName.setForeground(new java.awt.Color(51, 51, 51));
        productName.setAlignmentY(0.0F);
        jPanel1.add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, 30));

        jLabel7.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 102));
        jLabel7.setText("Product details");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 300, 160));

        jPanel2.setBackground(new java.awt.Color(78, 78, 78));

        jLabel12.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 102));
        jLabel12.setText("Description:");

        description.setColumns(20);
        description.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        description.setForeground(new java.awt.Color(51, 51, 51));
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        jLabel13.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 204, 102));
        jLabel13.setText("Product Description");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 540, 190));

        jPanel3.setBackground(new java.awt.Color(78, 78, 78));
        jPanel3.setForeground(new java.awt.Color(78, 78, 78));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(88, 66, 33));
        jLabel16.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 102));
        jLabel16.setText("Category:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 94, -1));
        jPanel3.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 60, -1));

        jLabel17.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 204, 102));
        jLabel17.setText("Retail Details");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 180, -1));

        cancel2.setBackground(new java.awt.Color(215, 127, 50));
        cancel2.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        cancel2.setForeground(new java.awt.Color(246, 214, 151));
        cancel2.setText("Cancel");
        cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel2ActionPerformed(evt);
            }
        });
        jPanel3.add(cancel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 358, -1, 23));

        jLabel18.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 204, 102));
        jLabel18.setText("Quantity:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 78, -1));

        jLabel10.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 102));
        jLabel10.setText("Cost Price:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 78, -1));

        jLabel11.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 102));
        jLabel11.setText("Sales Price:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        costprice.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        costprice.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(costprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, -1));

        jLabel15.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 102));
        jLabel15.setText("PKR");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 40, 20));

        salesprice.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 12)); // NOI18N
        salesprice.setForeground(new java.awt.Color(51, 51, 51));
        salesprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salespriceActionPerformed(evt);
            }
        });
        jPanel3.add(salesprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 80, -1));

        jLabel19.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 204, 102));
        jLabel19.setText("PKR");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 30, 20));
        jPanel3.add(Category1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 144, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 460, 150));

        remove.setBackground(new java.awt.Color(215, 127, 52));
        remove.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        remove.setForeground(new java.awt.Color(246, 214, 145));
        remove.setText("REMOVE");
        remove.setAlignmentX(0.5F);
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, -1, 37));

        cancel1.setBackground(new java.awt.Color(215, 127, 52));
        cancel1.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        cancel1.setForeground(new java.awt.Color(246, 214, 145));
        cancel1.setText("Cancel");
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 630, 98, 37));

        submit1.setBackground(new java.awt.Color(215, 127, 52));
        submit1.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        submit1.setForeground(new java.awt.Color(246, 214, 145));
        submit1.setText("ADD/UPDATE");
        submit1.setAlignmentX(0.5F);
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        getContentPane().add(submit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, -1, 37));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/I_M.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        DashBoard db= new DashBoard();
        db.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void productIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDActionPerformed

    private void cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel2ActionPerformed

    private void salespriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salespriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salespriceActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        
        
        if(!("".equals(Barcode.getText())  || "".equals(productID.getText())  ))
        {
        try{
            
            
            Barcode_NO=Barcode.getText();
            ProductID=Integer.parseInt(productID.getText());
            
          Data.setBarcode_No(Barcode_NO);
          Data.setProductID(ProductID);
          status=Data.RemoveInventory(Data);
            
            if(status==0)
            {
                JOptionPane.showMessageDialog(null,"Product Is Successfully Removed From The Inventory");
                Barcode.setText("");
                productID.setText("");
                productName.setText("");
                Category1.setText("");
                Quantity.setText("");
                costprice.setText("");
                salesprice.setText("");
                description.setText("");
            }
            else if(status==1)
            {
                JOptionPane.showMessageDialog(null,"This Product Doesn't exist");
                Barcode.setText("");
                productID.setText("");
                productName.setText("");
                Category1.setText("");
                Quantity.setText("");
                costprice.setText("");
                salesprice.setText("");
                description.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Error Found");
            }
        }
        catch(HeadlessException Ex)
        {
            //JOptionPane.showMessageDialog(null,e);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Enter BarCode and ProductID!");
        }
        //        DashBoard db = new DashBoard();
        //        this.setVisible(false);
        //        db.setVisible(true);
    }//GEN-LAST:event_removeActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        DashBoard db = new DashBoard();
        this.setVisible(false);
        db.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_cancel1ActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        
         if(!("".equals(Barcode.getText())  || "".equals(productID.getText())  || "".equals(productName.getText())
                    || "".equals(Category1.getText()) || "".equals(Quantity.getText())
                    || "".equals(salesprice.getText()) || "".equals(costprice.getText())|| "".equals(description.getText())))
        {
        try{
            
            
            Barcode_NO=Barcode.getText();
            ProductID=Integer.parseInt(productID.getText());
            ProductName=productName.getText();
            Categoryname=Category1.getText();
            
            Quantity1=Integer.parseInt(Quantity.getText());
            Cost_Price=Float.parseFloat(costprice.getText());
            Sales_Price=Float.parseFloat(salesprice.getText());
            Description=description.getText();

          Data.AddInventory(Barcode_NO, ProductID, ProductName, Categoryname, Quantity1, Cost_Price, Sales_Price, Description);
            status=Data.AddInventory(Data);
          if(status==0)
            {
                JOptionPane.showMessageDialog(null,"Product Is inserted Succesfully in Inventory");
                Barcode.setText("");
                productID.setText("");
                productName.setText("");
                Category1.setText("");
                Quantity.setText("");
                costprice.setText("");
                salesprice.setText("");
                description.setText("");
            }
            else if(status==1)
            {
                JOptionPane.showMessageDialog(null," Product Updated Successfully!");
                Barcode.setText("");
                productID.setText("");
                productName.setText("");
                Category1.setText("");
                Quantity.setText("");
                costprice.setText("");
                salesprice.setText("");
                description.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Error Found");
            }
        }
        catch(HeadlessException Ex)
        {
            JOptionPane.showMessageDialog(null,"Error Found");
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Fill all the fields!");
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        try{
            String url="jdbc:sqlserver://localhost:1433;databaseName=POS2;user=sa;password=sa1234";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(url);
            Barcode_NO=Barcode.getText();
            ProductID=Integer.parseInt(productID.getText());
            ProductName=productName.getText();
            Categoryname=Category1.getText();
            //              Integer myInt=(Integer) Quantity.getValue();
            //              spinner=myInt.toString();// TODO add your handling code here:
            Quantity1=Integer.parseInt(Quantity.getText());
            Cost_Price=Float.parseFloat(costprice.getText());
            Sales_Price=Float.parseFloat(salesprice.getText());
            Description=description.getText();

            csmt=con.prepareCall("{call InventoryManagement(?,?,?,?,?,?,?,?,?)}");
            csmt.setString(1, Barcode_NO);
            csmt.setInt(2, ProductID);
            csmt.setString(3, ProductName);
            csmt.setString(4, Categoryname);
            csmt.setInt(5, Quantity1);
            csmt.setFloat(6, Cost_Price);
            csmt.setFloat(7, Sales_Price);
            csmt.setString(8, Description);

            csmt.registerOutParameter(9, Types.INTEGER);
            csmt.executeUpdate();
            status= csmt.getInt(9);

            if(status==0)
            {
                JOptionPane.showMessageDialog(null,"Product Is Successfully Added Into The Inventory!");
                Barcode.setText("");
                productID.setText("");
                productName.setText("");
                Category1.setText("");
                Quantity.setText("");
                costprice.setText("");
                salesprice.setText("");
                description.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Product Details Are Successfully Updated!");
                Barcode.setText("");
                productID.setText("");
                productName.setText("");
                Category1.setText("");
                Quantity.setText("");
                costprice.setText("");
                salesprice.setText("");
                description.setText("");
            }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_submit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Barcode;
    private javax.swing.JTextField Category1;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton cancel2;
    private javax.swing.JTextField costprice;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField productID;
    private javax.swing.JTextField productName;
    private javax.swing.JButton remove;
    private javax.swing.JTextField salesprice;
    private javax.swing.JButton submit1;
    // End of variables declaration//GEN-END:variables
}
